config/routes.rb
Rails.application.routes.draw do
  root  'users#index',as:'users_index'


  get '/microposts'=>'microposts#index',as:'microposts_index'
  get '/microposts/new'=>'microposts#new',as:'microposts_new'
  get 'microposts/:id/edit'=>'microposts#edit',as:'microposts_edit'
  post 'microposts/create'=>'microposts#create',as:'microposts_create'
  patch 'microposts/:id/edit'=>'microposts#update',as:'microposts_update'
  delete 'microposts/:id/edit'=>'microposts#destroy',as:'microposts_destroy'
  get 'microposts/:id'=>'microposts#show',as:'microposts_show'

  get 'users/new'=>'users#new',as:'users_new'
  post'users/create'=>'users#create',as:'users_create'
  get 'users/:id/edit'=>'users#edit',as:'users_edit'
  patch 'users/:id/edit'=>'users#update',as:'users_update'
  delete 'users/:id/edit'=> 'users#destroy',as:'users_destroy'
  get 'users/:id'=> 'users#show',as:'users_show' 
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    validates :content, length: { maximum: 140 },
    presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :microposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def hello
      render html: "hello, world!"
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def index
    @microposts=Micropost.all
  end

  def show
  end

  def new
    @micropost=Micropost.new
  end

  def edit
  end

  def create
    @micropost=Micropost.new(micropost_params)
    if @micropost.save
       flash[:notice]="ユーザー登録が完了致しました。"
        redirect_to  microposts_show_path(@micropost.id)
    else
      render :index
    end
  end

  def update
  end

  def destroy
  end
private
def micropost_params
  params.require(:micropost).permit(:content,:user_id)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end
  def create
     @user=User.new(user_params)
    if @user.save
       session[:user_id]=@user.id
       flash[:notice]="ユーザー登録が完了致しました。"
        redirect_to  users_show_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user=User.find_by(id:params[:id])
  end

  def new
     @user=User.new
  end
  def update
    @user=User.find_by(id:params[:id])
    if @user.update(user_params) 
      flash[:notice]="プランナー情報を更新しました。"
      redirect_to users_show_path(@user.id)
    else
      render :index
    end
  end

  def edit
    @user=User.find_by(id:params[:id])
  end

  def destroy
    @user=User.find_by(id:params[:id])
    @user.destroy
    redirect_to users_index_path
  
  end
  private
  def user_params
    params.require(:user).permit(:name,:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppRailstutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/microposts/edit.html.erb
<h1>Microposts#edit</h1>
<p>Find me in app/views/microposts/edit.html.erb</p>

app/views/microposts/index.html.erb
<h1>Microposts#index</h1>
<p>Find me in app/views/microposts/index.html.erb</p>
<table>
    <thead>
        <tr>
            <th >content</th>
            <th>user</th>
        </tr>
    </thead>
    <%@microposts.each do |micropost|%>
      <tr> 
        <td><%=micropost.content%></td>
        <td><%=micropost.user_id%></td>
       
        <td><%=link_to 'show', microposts_show_path(micropost.id) %></td>
        <td><%=link_to 'Edit',microposts_edit_path(micropost.id)%></td>
        <td><%=link_to 'Destroy',microposts_destroy_path(micropost.id), method: :delete, data:{confirm: 'Are you sure?'}%></td>
      </tr>
    <%end%>
</table>
    <%=link_to "Newmicropost", microposts_new_path %>  

app/views/microposts/new.html.erb
<h1>Microposts#new</h1>
<p>Find me in app/views/microposts/new.html.erb</p>
<%=form_for @micropost,url:microposts_create_path do|f|%>
  <p><%=f.label :content %></p>
  <p><%= f.text_field :content, :placeholder => "content" %></p>
  <p> <%=f.label :user_id %></p>
  <p><%= f.text_field :user_id, :placeholder => "User email" %></p>
  <p><%=f.submit :update %></p>
<%end%>

app/views/microposts/show.html.erb
<h1>Microposts#show</h1>
<p>Find me in app/views/microposts/show.html.erb</p>

app/views/users/edit.html.erb
<%=form_for @user, url: users_update_path(@user.id) do |f| %>
  <p><%=f.label :name %></p>
  <p><%= f.text_field :name, :placeholder => "User name" %></p>
   <p> <%=f.label :email %></p>
  <p><%= f.text_field :email, :placeholder => "User email" %></p>
 <%=f.submit :update %>
<%end%>
<%=link_to "Back", users_index_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>


<table>
    <thead>
        <tr>
            <th >Name</th>
            <th>Email</th>
        </tr>
    </thead>
    <%@users.each do |user|%>
      <tr> 
        <td><%=user.name%></td>
        <td><%=user.email%></td>
       
        <td><%=link_to 'show', users_show_path(user.id) %></td>
        <td><%=link_to 'Edit',users_edit_path(user.id)%></td>
        <td><%=link_to 'Destroy',users_destroy_path(user.id), method: :delete, data:{confirm: 'Are you sure?'}%></td>
      </tr>
    <%end%>
</table>
    <%=link_to "登録", users_new_path %>  

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%=form_for @user, url: users_create_path do |f| %>
  <p><%=f.label :name %></p>
  <p><%= f.text_field :name, :placeholder => "User name" %></p>
   <p> <%=f.label :email %></p>
  <p><%= f.text_field :email, :placeholder => "User email" %></p>
 <%=f.submit :update %>
<%end%>
<%=link_to "Back", users_index_path %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>Name:<%=@user.name%></p>
<p>Email:<%=@user.email%></p>
<%=link_to "Edit",users_edit_path(@user.id)%>|
<%=link_to "Back", users_new_path(@user.id)%>
<%=link_to "home", users_index_path%>